//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWCF_eSports.ProxyJugador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JugadorEstadistica", Namespace="http://schemas.datacontract.org/2004/07/WCF_eSports")]
    [System.SerializableAttribute()]
    public partial class JugadorEstadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomHeroeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalAssistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalDeathsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalKillsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomHeroe {
            get {
                return this.NomHeroeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomHeroeField, value) != true)) {
                    this.NomHeroeField = value;
                    this.RaisePropertyChanged("NomHeroe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Round {
            get {
                return this.RoundField;
            }
            set {
                if ((object.ReferenceEquals(this.RoundField, value) != true)) {
                    this.RoundField = value;
                    this.RaisePropertyChanged("Round");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalAssists {
            get {
                return this.TotalAssistsField;
            }
            set {
                if ((this.TotalAssistsField.Equals(value) != true)) {
                    this.TotalAssistsField = value;
                    this.RaisePropertyChanged("TotalAssists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalDeaths {
            get {
                return this.TotalDeathsField;
            }
            set {
                if ((this.TotalDeathsField.Equals(value) != true)) {
                    this.TotalDeathsField = value;
                    this.RaisePropertyChanged("TotalDeaths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalKills {
            get {
                return this.TotalKillsField;
            }
            set {
                if ((this.TotalKillsField.Equals(value) != true)) {
                    this.TotalKillsField = value;
                    this.RaisePropertyChanged("TotalKills");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JugadorBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_eSports")]
    [System.SerializableAttribute()]
    public partial class JugadorBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipo {
            get {
                return this.EquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipoField, value) != true)) {
                    this.EquipoField = value;
                    this.RaisePropertyChanged("Equipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyJugador.IServicioJugador")]
    public interface IServicioJugador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJugador/RankingJugador", ReplyAction="http://tempuri.org/IServicioJugador/RankingJugadorResponse")]
        WebWCF_eSports.ProxyJugador.JugadorEstadistica[] RankingJugador(short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJugador/RankingJugador", ReplyAction="http://tempuri.org/IServicioJugador/RankingJugadorResponse")]
        System.Threading.Tasks.Task<WebWCF_eSports.ProxyJugador.JugadorEstadistica[]> RankingJugadorAsync(short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJugador/ListarPaisJugadores", ReplyAction="http://tempuri.org/IServicioJugador/ListarPaisJugadoresResponse")]
        WebWCF_eSports.ProxyJugador.JugadorBE[] ListarPaisJugadores(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJugador/ListarPaisJugadores", ReplyAction="http://tempuri.org/IServicioJugador/ListarPaisJugadoresResponse")]
        System.Threading.Tasks.Task<WebWCF_eSports.ProxyJugador.JugadorBE[]> ListarPaisJugadoresAsync(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJugador/ListarJugadoresPorEdad", ReplyAction="http://tempuri.org/IServicioJugador/ListarJugadoresPorEdadResponse")]
        WebWCF_eSports.ProxyJugador.JugadorBE[] ListarJugadoresPorEdad(short edad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioJugador/ListarJugadoresPorEdad", ReplyAction="http://tempuri.org/IServicioJugador/ListarJugadoresPorEdadResponse")]
        System.Threading.Tasks.Task<WebWCF_eSports.ProxyJugador.JugadorBE[]> ListarJugadoresPorEdadAsync(short edad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioJugadorChannel : WebWCF_eSports.ProxyJugador.IServicioJugador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioJugadorClient : System.ServiceModel.ClientBase<WebWCF_eSports.ProxyJugador.IServicioJugador>, WebWCF_eSports.ProxyJugador.IServicioJugador {
        
        public ServicioJugadorClient() {
        }
        
        public ServicioJugadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioJugadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJugadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioJugadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebWCF_eSports.ProxyJugador.JugadorEstadistica[] RankingJugador(short top) {
            return base.Channel.RankingJugador(top);
        }
        
        public System.Threading.Tasks.Task<WebWCF_eSports.ProxyJugador.JugadorEstadistica[]> RankingJugadorAsync(short top) {
            return base.Channel.RankingJugadorAsync(top);
        }
        
        public WebWCF_eSports.ProxyJugador.JugadorBE[] ListarPaisJugadores(string pais) {
            return base.Channel.ListarPaisJugadores(pais);
        }
        
        public System.Threading.Tasks.Task<WebWCF_eSports.ProxyJugador.JugadorBE[]> ListarPaisJugadoresAsync(string pais) {
            return base.Channel.ListarPaisJugadoresAsync(pais);
        }
        
        public WebWCF_eSports.ProxyJugador.JugadorBE[] ListarJugadoresPorEdad(short edad) {
            return base.Channel.ListarJugadoresPorEdad(edad);
        }
        
        public System.Threading.Tasks.Task<WebWCF_eSports.ProxyJugador.JugadorBE[]> ListarJugadoresPorEdadAsync(short edad) {
            return base.Channel.ListarJugadoresPorEdadAsync(edad);
        }
    }
}
