//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWCF_eSports.ProxyHeroe {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeroeBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_eSports")]
    [System.SerializableAttribute()]
    public partial class HeroeBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtributoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplejidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Atributo {
            get {
                return this.AtributoField;
            }
            set {
                if ((object.ReferenceEquals(this.AtributoField, value) != true)) {
                    this.AtributoField = value;
                    this.RaisePropertyChanged("Atributo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complejidad {
            get {
                return this.ComplejidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplejidadField, value) != true)) {
                    this.ComplejidadField = value;
                    this.RaisePropertyChanged("Complejidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyHeroe.IServicioHeroe")]
    public interface IServicioHeroe {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHeroe/HeroeComplejidad", ReplyAction="http://tempuri.org/IServicioHeroe/HeroeComplejidadResponse")]
        WebWCF_eSports.ProxyHeroe.HeroeBE[] HeroeComplejidad(string complejidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHeroe/HeroeComplejidad", ReplyAction="http://tempuri.org/IServicioHeroe/HeroeComplejidadResponse")]
        System.Threading.Tasks.Task<WebWCF_eSports.ProxyHeroe.HeroeBE[]> HeroeComplejidadAsync(string complejidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioHeroeChannel : WebWCF_eSports.ProxyHeroe.IServicioHeroe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioHeroeClient : System.ServiceModel.ClientBase<WebWCF_eSports.ProxyHeroe.IServicioHeroe>, WebWCF_eSports.ProxyHeroe.IServicioHeroe {
        
        public ServicioHeroeClient() {
        }
        
        public ServicioHeroeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioHeroeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHeroeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHeroeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebWCF_eSports.ProxyHeroe.HeroeBE[] HeroeComplejidad(string complejidad) {
            return base.Channel.HeroeComplejidad(complejidad);
        }
        
        public System.Threading.Tasks.Task<WebWCF_eSports.ProxyHeroe.HeroeBE[]> HeroeComplejidadAsync(string complejidad) {
            return base.Channel.HeroeComplejidadAsync(complejidad);
        }
    }
}
