//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_eSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_JUGADOR_PARTIDA
    {
        public int IdJugador { get; set; }
        public int IdEquipo { get; set; }
        public int IdPartida { get; set; }
        public int IdHeroe { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
        public int Assists { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual HEROE HEROE { get; set; }
        public virtual JUGADOR JUGADOR { get; set; }
        public virtual PARTIDA PARTIDA { get; set; }
    }
}
