//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_eSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PERSONAL
    {
        public int IdPersonal { get; set; }
        public int IdTorneo { get; set; }
        public System.DateTime FechaInicioContrato { get; set; }
        public System.DateTime FechaFinContrato { get; set; }
    
        public virtual PERSONAL PERSONAL { get; set; }
        public virtual TORNEO TORNEO { get; set; }
    }
}
