//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_eSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class JUGADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JUGADOR()
        {
            this.DETALLE_JUGADOR_PARTIDA = new HashSet<DETALLE_JUGADOR_PARTIDA>();
        }
    
        public int IdJugador { get; set; }
        public string ApeJugador { get; set; }
        public string NomJugador { get; set; }
        public string NickJugador { get; set; }
        public Nullable<int> EdadJugador { get; set; }
        public string PaisJugador { get; set; }
        public string CapJugador { get; set; }
        public string RolJugador { get; set; }
        public int IdEquipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_JUGADOR_PARTIDA> DETALLE_JUGADOR_PARTIDA { get; set; }
        public virtual EQUIPO EQUIPO { get; set; }
    }
}
