//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_eSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTIDA()
        {
            this.DETALLE_JUGADOR_PARTIDA = new HashSet<DETALLE_JUGADOR_PARTIDA>();
        }
    
        public int IdPartida { get; set; }
        public string RoundPartida { get; set; }
        public System.DateTime FechaPartida { get; set; }
        public string Team { get; set; }
        public string Score { get; set; }
        public string vsTeam { get; set; }
        public int IdTorneo { get; set; }
        public Nullable<int> TeamWinner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_JUGADOR_PARTIDA> DETALLE_JUGADOR_PARTIDA { get; set; }
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual TORNEO TORNEO { get; set; }
    }
}
