//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_eSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIZEPOOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRIZEPOOL()
        {
            this.PUESTO_PRIZEPOOL = new HashSet<PUESTO_PRIZEPOOL>();
        }
    
        public int IdPrizepool { get; set; }
        public int IdTorneo { get; set; }
        public decimal PrizepoolTotal { get; set; }
    
        public virtual TORNEO TORNEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUESTO_PRIZEPOOL> PUESTO_PRIZEPOOL { get; set; }
    }
}
