//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_eSports
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORNEO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TORNEO()
        {
            this.DETALLE_EQUIPO = new HashSet<DETALLE_EQUIPO>();
            this.DETALLE_PERSONAL = new HashSet<DETALLE_PERSONAL>();
            this.PARTIDA = new HashSet<PARTIDA>();
            this.PRIZEPOOL = new HashSet<PRIZEPOOL>();
        }
    
        public int IdTorneo { get; set; }
        public string NomTorneo { get; set; }
        public string OrgTorneo { get; set; }
        public string PaisTorneo { get; set; }
        public string LugarTorneo { get; set; }
        public System.DateTime FechaInicioTorneo { get; set; }
        public System.DateTime FechaFinTorneo { get; set; }
        public int IdJuego { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_EQUIPO> DETALLE_EQUIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_PERSONAL> DETALLE_PERSONAL { get; set; }
        public virtual JUEGO JUEGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTIDA> PARTIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIZEPOOL> PRIZEPOOL { get; set; }
    }
}
